version: '3'
services:
  db:
    restart: always
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    # volumes: # for hot reloading w/ npm run dev
    # - .:/app
    command: ['npm', 'run', 'start']
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - PORT
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    links:
      - db
