name: 'Test Report'
# fix https://github.com/dorny/test-reporter/issues/229
permissions:
  checks: write
on:
  workflow_run:
    workflows: ['Test'] # runs after Test workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: JEST Tests # Name of the check run which will be created
          path: '*.xml' # Path to test results (inside artifact .zip)
          reporter: jest-junit # Format of test results
